spring.application.name=pod.back
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pod_local}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pwd}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-stacktrace=never
server.error.include-message=always

springdoc.swagger-ui.enabled=${DEV:false}
springdoc.api-docs.enabled=${DEV:false}

baseUrl=${ENVURL:http://localhost:8080}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:false}

tokenExpiration=${TOKEN_EXPIRATION:30}

secretKey=${SECRET_KEY}
JwtExpiration=${JWT_EXPIRATION}